# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20180810_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_utente', models.IntegerField(default=0)),
                ('settore', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
