# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_admindata_aziende_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='settore',
            new_name='tipologia',
        ),
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
