# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_auto_20180815_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='number',
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='photo',
            field=models.ImageField(default=0, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
