# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20180815_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='image',
        ),
        migrations.AlterField(
            model_name='session',
            name='photo',
            field=models.ImageField(upload_to='qrcodes'),
        ),
    ]
