# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_auto_20180815_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='photo',
            field=models.ImageField(default='/static/image.jpg', upload_to='qrcodes'),
        ),
    ]
