# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_auto_20180815_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='photo',
        ),
    ]
