# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_remove_session_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='photo',
            field=models.ImageField(default='/static/image.jpg', upload_to='qrcodes'),
        ),
    ]
