# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_session_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='photo',
            new_name='qrcode',
        ),
    ]
