# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_auto_20180815_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='note2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
