# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_session_note2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='note2',
        ),
        migrations.AlterField(
            model_name='session',
            name='tipologia',
            field=models.TextField(),
        ),
    ]
