# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0013_auto_20180815_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hash',
            field=models.TextField(default=b'65050963555622035374908726435581239581'),
        ),
    ]
