# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0014_session_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'191605595627511489344739848483164779320', max_length=128),
        ),
        migrations.AlterField(
            model_name='session',
            name='qrcode',
            field=models.CharField(max_length=400),
        ),
    ]
