# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_auto_20180815_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settore',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='yob',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'150588225395009880196565909658649588368', max_length=128),
        ),
    ]
