# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_auto_20180820_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'310710459259056379137959493344795754263', max_length=128),
        ),
    ]
