# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0017_auto_20180821_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'321748873941754446379696806265884002595', max_length=128),
        ),
    ]
