# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0018_auto_20180821_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'244789738048441862020071341214251296859', max_length=128),
        ),
    ]
