# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0019_auto_20180821_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('user', models.IntegerField(default=0)),
                ('session', models.CharField(max_length=128)),
                ('item1', models.IntegerField(default=1)),
                ('item2', models.IntegerField(default=2)),
                ('item3', models.IntegerField(default=3)),
                ('item4', models.IntegerField(default=4)),
                ('item5', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AlterField(
            model_name='session',
            name='hash',
            field=models.CharField(default=b'88021006326812980989316152350804553316', max_length=128),
        ),
    ]
