# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0022_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yob',
            field=models.IntegerField(default=1988),
        ),
    ]
