# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0023_auto_20180821_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yob',
            field=models.IntegerField(default=0),
        ),
    ]
