# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0024_auto_20180821_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='yob',
            field=models.CharField(max_length=4),
        ),
    ]
