# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0025_auto_20180821_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classe_utente',
        ),
    ]
