# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0026_remove_user_classe_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='risposta',
            name='tempo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='session',
            name='tempo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='tempo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
