# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0027_auto_20180822_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
