# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0028_auto_20180822_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='employer_averages',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admindata',
            name='uni_averages',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='aperta',
            field=models.BooleanField(default='False'),
        ),
    ]
