# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0030_auto_20180824_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='risposta',
            name='sessionkey',
            field=models.ForeignKey(default=12345667891, on_delete=django.db.models.deletion.CASCADE, to='career.Session'),
            preserve_default=False,
        ),
    ]
