# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0031_risposta_sessionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risposta',
            name='sessionkey',
        ),
        migrations.AlterField(
            model_name='session',
            name='tipologia',
            field=models.TextField(default='UNI'),
        ),
    ]
